version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 4000:4000
    volumes:
      - ./app:/app
    depends_on:
      - users_db

  users_db:
    image: postgres
    ports:
      - 5436:5432
    environment:
      POSTGRES_DB: users
      POSTGRES_PASSWORD: default_pw